# SITE CONFIGURATION
baseurl: "/"
url: "https://dev-iann.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Developer Iann
email: dev.iaannnn@gmail.com
description: >-  
  A blog to share development knowlegde and experince.
# avatar: assets/img/avatar.png
# favicon: assets/favicon/ico

# Header and footer text
# Theme customization
header_text: Tech Blog
header_feature_image: assets/images/starnightland.jpg
header_feature_image_responsive: true
fotter_text: "A blog to share development knowlegde and experince."

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics: G-5M0YXNKNMN                          # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: dark                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo: dev-iann/dev-iann.github.io                   # your public comments repository (e.g. owner/repo)
    issue-term: og:title                                # Issue term (e.g. "comment" consider issues with this word in the title as comments)
    theme: photon-dark
    label: Comment

# PAGINATION
paginate: 10
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

remote_theme: sylhare/Type-on-Strap
